-- Corrected PostgreSQL Schema for Chat Application
DROP DATABASE IF EXISTS ql_ungdungchat_v2;
CREATE DATABASE ql_ungdungchat_v2;
\c ql_ungdungchat_v2;

-- Table: MAUNEN (Theme/Background Color)
CREATE TABLE MAUNEN (
    ID_MAUNEN VARCHAR(20) PRIMARY KEY,
    TENMAUNEN VARCHAR(200)
);

-- Table: USERS
CREATE TABLE USERS (
    USERID VARCHAR(20) PRIMARY KEY,
    USERNAME VARCHAR(100) UNIQUE NOT NULL,
    PASSWORD VARCHAR(255) NOT NULL,
    NICKNAME VARCHAR(300)
);

-- Table: CHATROOM
CREATE TABLE CHATROOM (
    ID_CHATROOM VARCHAR(20) PRIMARY KEY,
    NGAYLAP DATE,
    ID_CHUDE VARCHAR(20),
    TENCHATROOM VARCHAR(200),
    CONSTRAINT FK_CHATROOM_MAUNEN FOREIGN KEY (ID_CHUDE) REFERENCES MAUNEN (ID_MAUNEN)
);

-- Table: CHATROOM_MEMBER
CREATE TABLE CHATROOM_MEMBER (
    ID_CHATROOM VARCHAR(20) NOT NULL,
    ID_NGUOINHAN VARCHAR(20) NOT NULL,
    NGAYTHAMGIA TIMESTAMP,
    NGAYROIDI TIMESTAMP,
    PRIMARY KEY (ID_CHATROOM, ID_NGUOINHAN),
    CONSTRAINT FK_CHATROOM_MEMBER_CHATROOM FOREIGN KEY (ID_CHATROOM) REFERENCES CHATROOM (ID_CHATROOM),
    CONSTRAINT FK_CHATROOM_MEMBER_USER FOREIGN KEY (ID_NGUOINHAN) REFERENCES USERS (USERID)
);

-- Table: MESSAGE
CREATE TABLE MESSAGE (
    ID_MESSAGE VARCHAR(100) PRIMARY KEY,
    ID_CHATROOM VARCHAR(20),
    NOIDUNGTN TEXT,
    NGUOIGUI VARCHAR(20),
    THOIGIANGUI TIMESTAMP,
    CONSTRAINT FK_MESSAGE_CHATROOM FOREIGN KEY (ID_CHATROOM) REFERENCES CHATROOM (ID_CHATROOM),
    CONSTRAINT FK_MESSAGE_USER FOREIGN KEY (NGUOIGUI) REFERENCES USERS (USERID)
);

-- Table: ATTACHMENT
CREATE TABLE ATTACHMENT (
    ID_ATTACH SERIAL PRIMARY KEY,
    ID_MESSAGE VARCHAR(100),
    FILE_URL VARCHAR(200),
    IMG_URL VARCHAR(200),
    CREATE_AT TIMESTAMP,
    CONSTRAINT FK_ATTACHMENT_MESSAGE FOREIGN KEY (ID_MESSAGE) REFERENCES MESSAGE (ID_MESSAGE)
);

-- Table: CHATROOM_USER (additional relationship table)
CREATE TABLE CHATROOM_USER (
    ID_CHATROOM VARCHAR(20) NOT NULL,
    USER_ID VARCHAR(20) NOT NULL,
    PRIMARY KEY (ID_CHATROOM, USER_ID),
    CONSTRAINT FK_CHATROOM_USER_CHATROOM FOREIGN KEY (ID_CHATROOM) REFERENCES CHATROOM (ID_CHATROOM),
    CONSTRAINT FK_CHATROOM_USER_USER FOREIGN KEY (USER_ID) REFERENCES USERS (USERID)
);
